import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'


export default function Home() {
  const [text, setText] = useState<string | null>(null);
  const [inText, setInText] = useState<string | null>(null);
  const [value, setValue] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  const insert = (data: any) => {
    setValue(data.target.value);
  }
  const handleClick = (): void => {
    if (inputRef.current !== null) {
      setInText(inputRef.current?.value);
      console.log(inputRef.current?.value);

    }
    setValue('');
  }

  useEffect(() => {

    fetch('api/contact', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ inData: inText })
    })
      .then((Response) => Response.json())
      .then((getter) => setText(getter.text))
      .catch((error) => console.log(error));
    setTimeout(() => {
      setText(null);
    }, 2000);
  }, [inText]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='wrapper'>
        <h3>api test</h3>
        <input onChange={insert} ref={inputRef} value={value} type="text" />
        <button onClick={handleClick}>Push api</button>
        <hr />
        {text}
      </div>
    </>
  )
}
